### ISSUE TITLE
choose library to sync from

### ISSUE THREAD

**Issue by bklaydman** [zeroheight/library-styles-sync#1]
One of the greatest plugins, thank you. Is there a way to select which library (sometimes we use multiples) the styles are pulled from? Rather than inserting an object from the library, I would like to run a plugin that prompts the library selection and just pulled the styles from it.

**Comment by robintindale** [comment]
Thank you! 

There isn't currently a way of selecting the library, no, but it would be pretty easy to add. We could just add another action to the menu which is something along the lines of "Choose and Sync"

**Comment by bklaydman** [comment]
Would you please add it? I would love to be able to select the library. Could be a separate command if need be in order to keep existing sync as is. 

Thank you in advance,

Boris

**Comment by DaveG43** [comment]
+1. Great plugin - would love a menu item (like the symbol swapper plugin).

**Comment by robintindale** [comment]
Fixed by #5 and released as `1.0.5`
