### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by fbchrt** [zeroheight/library-styles-sync#4]
Hello,

I installed the plugin yesterday and initially it worked. Today, however, when executing the Sync command in a new Sketch file I just get "Synced styles with 0 libraries" and that's it. However, there is 1 library set to active and this library has a lot of styles in it.

Any ideas?

**Comment by robintindale** [comment]
Perhaps that the current file doesn't have any symbols inserted from that library? That's currently how the plugin works out which library to sync styles from. Try inserting a symbol from the library you want to sync from, and retrying the plugin. Also keep an eye on #1, as this will prevent having to insert a symbol

**Comment by fbchrt** [comment]
Oh, of course ... that's also mentioned in the readme. Shame on me and thank you!

Just a suggestion: Maybe make it more clear how the plugin works by entering a section like

> How to use the plugin:
> 
> 1. Insert a symbol from the library you want to sync the styles from.
> 2. Run the Sync command.

instead of just mentioning it in another section. This might help lazy people like me find it, instead of bothering you! :)

**Comment by robintindale** [comment]
sure - updated the README 😁
