### ISSUE TITLE
issues with Sketch 50

### ISSUE THREAD

**Issue by nobita18** [zeroheight/library-styles-sync#7]
This plugin has been working like a charm but it seems that the plugin stopped working when Sketch app got updated to 5.0. Any thoughts?

**Comment by robintindale** [comment]
Taking a look

**Comment by nobita18** [comment]
Awesome! Much appreciated, @robintindale !

**Comment by robintindale** [comment]
1.0.6 should fix the Sketch 50 issues https://github.com/zeroheight/library-styles-sync/releases/download/1.0.6/library-styles-sync.sketchplugin.zip

**Comment by nobita18** [comment]
It's fixed! Thanks a bunch!!!
