### ISSUE TITLE
Support for Abstract

### ISSUE THREAD

**Issue by raylinmarie** [zeroheight/library-styles-sync#8]
We're using Abstract, but since Abstract works with branches, it ends up creating multiple uploads in Zeroheight. Is there any support for working with Abstract?

**Comment by robintindale** [comment]
I assume you're talking about the zeroheight.com Sketch plugin - not `library-styles-sync`? If so, I'd recommend joining our Spectrum community, which you can do from the zeroheight website when you're logged in. Open the top right dropdown and click "Suggest a feature". There are threads discussing using Abstract with zeroheight
